### ISSUE TITLE
Class "Doctrine\Common\Lexer\AbstractLexer" not found 

### ISSUE THREAD

**Issue by dfangx** [timhae/firefly#18]
First off, thanks for packaging this as a flake. I am trying to use this flake on my Raspberry Pi 4. I am getting the error `Class "Doctrine\Common\Lexer\AbstractLexer" not found` when attempting to register an account. The following is in my `flake.nix`
```
inputs = {
  ...
  firefly.url = "github:timhae/firefly";
  firefly.inputs.nixpkgs.follows = "nixos";
  nixos.url = "github:NixOS/nixpkgs/nixos-22.11";
};
..
outputs = { nixpkgs, home-manager, ... }@inputs:
...
{
  ...
  slothpi = nixpkgs.lib.nixosSystem {
    modules = [
      ...
      {
        ...
        inputs.firefly.overlays.default
      }
      inputs.firefly.nixosModules.firefly-iii
    ];
  };
};
```
The following is in my configuration.nix:
```
{ config, ... }:
let
  inherit (config.networking) domain hostName;
  fqdn = "finance.${hostName}.${domain}";
in
{
  services.firefly-iii = {
    enable = true;
    appURL = "https://${fqdn}";
    appKeyFile = config.age.secrets.fireflyIII.path;
    hostname = fqdn;
    nginx = {
      serverAliases = [
        fqdn
      ];
      useACMEHost = "${hostName}.${domain}";
      forceSSL = true;
    };
    group = "nginx";
    database.createLocally = true;
  };
}
```
Anything that I may have misconfigured?

**Comment by timhae** [comment]
Hey, your'e welcome! Have you set the file permissions for the agenix appkey accordingly? Other than that nothing seems off.. I am not sure about the nginx configuration but this rather looks like a php/lavarel issue.. I can try to update the dependencies on friday.

**Comment by dfangx** [comment]
Thanks for the reply. I've set the permissions as follows:
```
   fireflyIII = {
      file = ./secrets/fireflyIII.age;
      mode = "770";
      owner = "firefly-iii";
      group = "nginx";
    };
```
To me, it looks alright. The nginx configuration should be fine - its similar to the other virtual hosts I have set up on my machine, just different hostname.

**Comment by timhae** [comment]
I will also try to setup an arm64 github runner to catch stuff like this..

**Comment by timhae** [comment]
The arm [build](https://github.com/timhae/firefly/actions/runs/4322128427/jobs/7544160851) was successful, unfortunately I don't have a pi4 at hand to test it directly and as they are quite expensive at the moment I am afraid that won't happen anytime soon.. There is a firefly update to 6.0.0 that I will try to integrate now, maybe that will help you out.

**Comment by timhae** [comment]
Sorry, I don't think I can help you, maybe try upgrading to v6.0.0, the [build](https://github.com/timhae/firefly/actions/runs/4331817546/jobs/7563898931) was also green there. I can't reproduce the issue in CI and I don't have an arm64 device :(

**Comment by dfangx** [comment]
Thanks, I will give that a shot, thanks for your time!

**Comment by timhae** [comment]
I just saw that you didn't have any issues during building only when creating a user, sorry :D I did not check that yet but will probably try on sunday and see if I have the same issue..

**Comment by dfangx** [comment]
Haha no worries! I tried the updated flake and I was able to get it work! Thanks!
